### ISSUE TITLE
Namespace info in document

### ISSUE THREAD

**Issue by talk2cerlin** [AnujRNair/php-json-marshaller#3]
I came across this line `new JsonMarshaller(new ClassDecoder(new DoctrineAnnotationReader()));` in document in which the namespace info is not present.

It would be easy for others if the namespace info is available in a `use` statement before the above mentioned line.

I had to go through the source code to find out the namespace.

**Comment by talk2cerlin** [comment]
Also i would recommend to put license info in `composer.json`

**Comment by AnujRNair** [comment]
Thanks! I've added the info here: https://github.com/AnujRNair/php-json-marshaller/pull/4

**Comment by talk2cerlin** [comment]
even now the `MarshallProperty` is not namespaced properly.

**Comment by AnujRNair** [comment]
Thanks, I've added those too
