### ISSUE TITLE
Is there anyway i can convert a property of a class to STDCLASS?

### ISSUE THREAD

**Issue by talk2cerlin** [AnujRNair/php-json-marshaller#5]
I have converted my json to a class object using your marshaller. only problem is the sub properties are string. I donot have an entity object to map to those data. 

so is there anyway your system supports stdclass like it would convert in json decode?

**Comment by AnujRNair** [comment]
@talk2cerlin - At the moment there is not a way to do this, however, I will accept a PR if you would like to add that feature in!

Thanks
