### ISSUE TITLE
Can we get a 1.0.1 release?

### ISSUE THREAD

**Issue by SilverPreece** [AnujRNair/php-json-marshaller#7]
There are several useful additions to the codebase since the 1.0.0 release, such as the ability to pass a "do not encode" flag. I forked the repo to add a feature only to find that it already exists. It would be nice to get a 1.0.1 release up on Packagist so we can more easily take advantage of these additions.

**Comment by AnujRNair** [comment]
Hi there!
As soon as I'm back from vacation in a couple of weeks, I'll do this!

**Comment by AnujRNair** [comment]
This has now been done, apologies for the delay!
